apiVersion: v1
kind: Pod
metadata:
  name: myvolhostpath
spec:
  containers:
  - image: centos
    name: testc
    command: ["/bin/bash", "-c", "sleep 15000"]
    volumeMounts:
    - mountPath: /tmp/hostpathnew
      name: testvolume
  volumes:
  - name: testvolume
    hostPath:
      path: /home/master1/volumes
      type: DirectoryOrCreate
